/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. */
package cn.zhuatech.mdm.model;
import jakarta.persistence.*;import java.math.BigDecimal;import java.time.LocalDate;
@Entity @Table(name="mdm_purchase_order") public class PurchaseOrder extends BaseEntity {
    @Column(nullable=false,unique=true,length=32) private String orderNo;@ManyToOne(fetch=FetchType.LAZY,optional=false) private Supplier supplier;@ManyToOne(fetch=FetchType.LAZY,optional=false) private Material material;@Column(nullable=false,precision=14,scale=2) private BigDecimal quantity;@Column(nullable=false,precision=14,scale=2) private BigDecimal unitPrice;@Column(nullable=false) private LocalDate expectedDate;@Column(nullable=false,length=24) private String status;@Column(nullable=false,precision=14,scale=2) private BigDecimal receivedQty=BigDecimal.ZERO;
    protected PurchaseOrder(){} public PurchaseOrder(String orderNo,Supplier supplier,Material material,BigDecimal quantity,BigDecimal unitPrice,LocalDate expectedDate,String status){this.orderNo=orderNo;this.supplier=supplier;this.material=material;this.quantity=quantity;this.unitPrice=unitPrice;this.expectedDate=expectedDate;this.status=status;}
    public String getOrderNo(){return orderNo;} public Supplier getSupplier(){return supplier;} public Material getMaterial(){return material;} public BigDecimal getQuantity(){return quantity;} public BigDecimal getUnitPrice(){return unitPrice;} public LocalDate getExpectedDate(){return expectedDate;} public String getStatus(){return status;} public BigDecimal getReceivedQty(){return receivedQty;} public BigDecimal getAmount(){return quantity.multiply(unitPrice);}
    public void approve(){if("草稿".equals(status))status="待交付";} public void receive(BigDecimal qty){receivedQty=receivedQty.add(qty);material.receive(qty);status=receivedQty.compareTo(quantity)>=0?"已完成":"部分到货";}
}
