/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. · https://www.zhuatech.cn/ */
package cn.zhuatech.mdm.controller;
import cn.zhuatech.mdm.common.ApiResponse;import cn.zhuatech.mdm.dto.MdmDto.*;import cn.zhuatech.mdm.service.MdmService;import jakarta.validation.Valid;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import java.util.List;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@RestController @RequestMapping("/api/mdm") @PreAuthorize("hasAnyRole('ADMIN','PLANNER','BUYER')") public class SupplyChainController {
 private final MdmService service;/**
                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                   */
public SupplyChainController(MdmService service){this.service=service;}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @GetMapping("/dashboard") public ApiResponse<Dashboard> dashboard(){return ApiResponse.ok(service.dashboard());}/**
                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                  */
@GetMapping("/suppliers") public ApiResponse<List<SupplierView>> suppliers(){return ApiResponse.ok(service.suppliers());}/**
                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                           */
@GetMapping("/materials") public ApiResponse<List<MaterialView>> materials(){return ApiResponse.ok(service.materials());}/**
                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                    */
@GetMapping("/demands") public ApiResponse<List<DemandView>> demands(){return ApiResponse.ok(service.demands());}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
@GetMapping("/orders") public ApiResponse<List<OrderView>> orders(){return ApiResponse.ok(service.orders());}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
@GetMapping("/alerts") public ApiResponse<List<AlertView>> alerts(){return ApiResponse.ok(service.alerts());}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @PostMapping("/demands") @PreAuthorize("hasAnyRole('ADMIN','PLANNER')") public ApiResponse<DemandView> createDemand(@Valid @RequestBody CreateDemandRequest r){return ApiResponse.ok("数据标准已创建",service.createDemand(r));}/**
                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                           */
@PostMapping("/orders") @PreAuthorize("hasAnyRole('ADMIN','BUYER')") public ApiResponse<OrderView> createOrder(@Valid @RequestBody CreateOrderRequest r){return ApiResponse.ok("变更申请已创建",service.createOrder(r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                             */
@PostMapping("/orders/{id}/approve") @PreAuthorize("hasRole('ADMIN')") public ApiResponse<OrderView> approve(@PathVariable Long id){return ApiResponse.ok("变更申请已审核",service.approve(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
@PostMapping("/orders/{id}/receive") public ApiResponse<OrderView> receive(@PathVariable Long id,@Valid @RequestBody ReceiveRequest r){return ApiResponse.ok("到货数量已登记",service.receive(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
@PostMapping("/alerts/{id}/close") public ApiResponse<AlertView> closeAlert(@PathVariable Long id){return ApiResponse.ok("主数据预警已关闭",service.closeAlert(id));}
}
