/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.mdm.deep;import cn.zhuatech.mdm.common.ApiResponse;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@RestController @RequestMapping("/api/admin/mdm-ops") @PreAuthorize("hasRole('ADMIN')") public class DeepMasterDataAdminController{private final DeepMasterDataService s;/**
                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                          */
public DeepMasterDataAdminController(DeepMasterDataService x){s=x;}/**
                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                             */
@PostMapping("/domains")ApiResponse<?> domain(@RequestBody DeepMasterDataService.DomainInput x){return ApiResponse.ok(s.createDomain(x));}/**
                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                       */
@PostMapping("/domains/{id}/activate")ApiResponse<?> activate(@PathVariable Long id){return ApiResponse.ok(s.activate(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
@PostMapping("/records/{id}/steward")ApiResponse<?> steward(@PathVariable Long id,@RequestBody DeepMasterDataService.StewardDecision x){return ApiResponse.ok(s.steward(id,x));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
@PostMapping("/changes/{id}/approve")ApiResponse<?> approve(@PathVariable Long id,@RequestBody DeepMasterDataService.ApprovalInput x){return ApiResponse.ok(s.approveChange(id,x));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
@PostMapping("/outbox/{id}/send")ApiResponse<?> send(@PathVariable Long id){return ApiResponse.ok(s.send(id));}}
