/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.mdm.deep;import cn.zhuatech.mdm.common.ApiResponse;import org.springframework.web.bind.annotation.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@RestController @RequestMapping("/api/mdm-ops") public class DeepMasterDataController{private final DeepMasterDataService s;/**
                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                             */
public DeepMasterDataController(DeepMasterDataService x){s=x;}/**
                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                           */
@GetMapping("/workspace")ApiResponse<?> workspace(){return ApiResponse.ok(s.workspace());}/**
                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                     */
@PostMapping("/domains/{id}/records")ApiResponse<?> ingest(@PathVariable Long id,@RequestBody DeepMasterDataService.RecordInput x){return ApiResponse.ok(s.ingest(id,x));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
@PostMapping("/records/{id}/submit")ApiResponse<?> submit(@PathVariable Long id){return ApiResponse.ok(s.submit(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
@PostMapping("/changes")ApiResponse<?> change(@RequestBody DeepMasterDataService.ChangeInput x){return ApiResponse.ok(s.requestChange(x));}}
