/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.mdm.deep;import jakarta.persistence.*;import org.springframework.http.*;import org.springframework.stereotype.*;import org.springframework.transaction.annotation.*;import org.springframework.web.server.*;import java.time.*;import java.util.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Service @Transactional(readOnly=true) public class DeepMasterDataService{private final EntityManager em;/**
                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                          */
public DeepMasterDataService(EntityManager e){em=e;}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public DomainView createDomain(DomainInput x){if(x.matchThreshold()<50||x.matchThreshold()>100)throw bad("匹配阈值应在50到100之间");var d=new MasterDomain(x.domainCode(),x.name(),x.keyField(),x.matchThreshold());em.persist(d);audit("CREATE_DOMAIN",x.domainCode(),x.name());return view(d);}/**
                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                         */
@Transactional public DomainView activate(Long id){var d=domain(id);if(!"DRAFT".equals(d.status))throw conflict("主数据域不可启用");d.status="ACTIVE";return view(d);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public RecordView ingest(Long domainId,RecordInput x){var d=domain(domainId);if(!"ACTIVE".equals(d.status))throw conflict("主数据域尚未启用");var r=new MasterRecord(domainId,x.recordNo(),x.sourceSystem(),x.businessKey(),x.name(),x.identityNo());em.persist(r);audit("INGEST_RECORD",x.recordNo(),x.sourceSystem());return view(r);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public SubmitResult submit(Long id){var r=record(id);if(!"DRAFT".equals(r.status))throw conflict("记录状态不可提交");var d=domain(r.domainId);var list=em.createQuery("select r from MasterRecord r where r.domainId=:d and r.id<>:id and r.status='GOLDEN'",MasterRecord.class).setParameter("d",r.domainId).setParameter("id",r.id).getResultList();int created=0;for(var c:list){int score=Objects.equals(r.identityNo,c.identityNo)&&r.identityNo!=null&&!r.identityNo.isBlank()?100:Objects.equals(r.normalizedName,c.normalizedName)?85:0;if(score>=d.matchThreshold){em.persist(new MatchCandidate(r.id,c.id,score));created++;}}r.status="IN_REVIEW";return new SubmitResult(view(r),created);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public RecordView steward(Long id,StewardDecision x){var r=record(id);if(!"IN_REVIEW".equals(r.status))throw conflict("仅待治理记录可裁决");if("CREATE_GOLDEN".equals(x.decision())){r.status="GOLDEN";r.goldenId=r.id;}else if("MERGE".equals(x.decision())){var g=record(Objects.requireNonNull(x.goldenRecordId(),"goldenRecordId"));if(!"GOLDEN".equals(g.status)||!g.domainId.equals(r.domainId))throw conflict("目标黄金记录无效");r.status="MERGED";r.goldenId=g.id;matches(r.id).forEach(m->m.status=m.candidateId.equals(g.id)?"CONFIRMED":"REJECTED");}else throw bad("裁决仅支持CREATE_GOLDEN或MERGE");audit("STEWARD_DECISION",r.recordNo,x.decision());return view(r);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public ChangeView requestChange(ChangeInput x){var g=record(x.goldenRecordId());if(!"GOLDEN".equals(g.status))throw conflict("只能变更黄金记录");String old=switch(x.fieldName()){case"name"->g.name;case"identityNo"->g.identityNo;default->throw bad("仅允许变更name或identityNo");};var c=new MasterChangeRequest(x.changeNo(),g.id,x.fieldName(),old,x.newValue(),x.reason());em.persist(c);return view(c);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public ChangeView approveChange(Long id,ApprovalInput x){var c=change(id);if(!"PENDING".equals(c.status))throw conflict("变更申请状态不可审批");if(!x.approved()){c.status="REJECTED";return view(c);}var g=record(c.goldenRecordId);if("name".equals(c.fieldName)){g.name=c.newValue;g.normalizedName=c.newValue.replaceAll("\\s+","").toUpperCase();}else g.identityNo=c.newValue;c.status="APPROVED";em.persist(new DistributionOutbox("EVT-"+c.changeNo,g.id,x.targetSystem()));audit("APPROVE_CHANGE",c.changeNo,c.fieldName);return view(c);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public OutboxView send(Long id){var o=outbox(id);if(!"PENDING".equals(o.status)&&!"FAILED".equals(o.status))throw conflict("事件不可发送");o.status="SENT";o.sentAt=LocalDateTime.now();return view(o);}/**
                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                   */
public Workspace workspace(){return new Workspace(domains(),records(),changes(),outboxes());}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private MasterDomain domain(Long id){var x=em.find(MasterDomain.class,id);if(x==null)throw missing("主数据域不存在");return x;}/**
                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                          */
private MasterRecord record(Long id){var x=em.find(MasterRecord.class,id);if(x==null)throw missing("主数据记录不存在");return x;}/**
                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                   */
private MasterChangeRequest change(Long id){var x=em.find(MasterChangeRequest.class,id);if(x==null)throw missing("变更申请不存在");return x;}/**
                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                         */
private DistributionOutbox outbox(Long id){var x=em.find(DistributionOutbox.class,id);if(x==null)throw missing("分发事件不存在");return x;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
private List<MatchCandidate>matches(Long r){return em.createQuery("select m from MatchCandidate m where m.recordId=:r",MatchCandidate.class).setParameter("r",r).getResultList();}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
private void audit(String a,String n,String d){em.persist(new MasterAudit(a,n,d));}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private List<DomainView>domains(){return em.createQuery("select d from MasterDomain d order by d.id desc",MasterDomain.class).getResultList().stream().map(this::view).toList();}/**
                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                   */
private List<RecordView>records(){return em.createQuery("select r from MasterRecord r order by r.id desc",MasterRecord.class).getResultList().stream().map(this::view).toList();}/**
                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                    */
private List<ChangeView>changes(){return em.createQuery("select c from MasterChangeRequest c order by c.id desc",MasterChangeRequest.class).getResultList().stream().map(this::view).toList();}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
private List<OutboxView>outboxes(){return em.createQuery("select o from DistributionOutbox o order by o.id desc",DistributionOutbox.class).getResultList().stream().map(this::view).toList();}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private DomainView view(MasterDomain d){return new DomainView(d.id,d.domainCode,d.name,d.keyField,d.matchThreshold,d.status,d.lockVersion);}/**
                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                              */
private RecordView view(MasterRecord r){return new RecordView(r.id,r.domainId,r.recordNo,r.sourceSystem,r.businessKey,r.name,r.identityNo,r.status,r.goldenId,r.lockVersion);}/**
                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                            */
private ChangeView view(MasterChangeRequest c){return new ChangeView(c.id,c.changeNo,c.goldenRecordId,c.fieldName,c.oldValue,c.newValue,c.status,c.lockVersion);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
private OutboxView view(DistributionOutbox o){return new OutboxView(o.id,o.eventNo,o.recordId,o.targetSystem,o.status,o.retries,o.sentAt);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}/**
                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                              */
private ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}/**
                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                            */
private ResponseStatusException missing(String m){return new ResponseStatusException(HttpStatus.NOT_FOUND,m);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 public record DomainInput(String domainCode,String name,String keyField,int matchThreshold){}/**
                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                               */
public record RecordInput(String recordNo,String sourceSystem,String businessKey,String name,String identityNo){}/**
                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                */
public record StewardDecision(String decision,Long goldenRecordId){}/**
                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                    */
public record ChangeInput(String changeNo,Long goldenRecordId,String fieldName,String newValue,String reason){}/**
                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                   */
public record ApprovalInput(boolean approved,String targetSystem){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
public record DomainView(Long id,String domainCode,String name,String keyField,int matchThreshold,String status,long version){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
public record RecordView(Long id,Long domainId,String recordNo,String sourceSystem,String businessKey,String name,String identityNo,String status,Long goldenId,long version){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
public record SubmitResult(RecordView record,int candidateCount){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
public record ChangeView(Long id,String changeNo,Long goldenRecordId,String fieldName,String oldValue,String newValue,String status,long version){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */
public record OutboxView(Long id,String eventNo,Long recordId,String targetSystem,String status,int retries,LocalDateTime sentAt){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
public record Workspace(List<DomainView>domains,List<RecordView>records,List<ChangeView>changes,List<OutboxView>outbox){}
}
