/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. */
package cn.zhuatech.mdm.service;
import cn.zhuatech.mdm.common.BusinessException;import cn.zhuatech.mdm.dto.MdmDto.*;import cn.zhuatech.mdm.model.*;import cn.zhuatech.mdm.repository.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.List;
@Service @Transactional(readOnly=true) public class MdmService {
 private final SupplierRepository suppliers;private final MaterialRepository materials;private final DemandPlanRepository demands;private final PurchaseOrderRepository orders;private final SupplyAlertRepository alerts;
 public MdmService(SupplierRepository suppliers,MaterialRepository materials,DemandPlanRepository demands,PurchaseOrderRepository orders,SupplyAlertRepository alerts){this.suppliers=suppliers;this.materials=materials;this.demands=demands;this.orders=orders;this.alerts=alerts;}
 public Dashboard dashboard(){var all=orders.findAllByOrderByExpectedDateAsc();var amount=all.stream().map(PurchaseOrder::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add);long delayed=all.stream().filter(o->o.getExpectedDate().isBefore(LocalDate.now())&&!"已完成".equals(o.getStatus())).count();long low=materials.findAll().stream().filter(m->m.getCurrentStock().compareTo(m.getSafetyStock())<0).count();return new Dashboard(demands.countByStatus("待转采购"),all.stream().filter(o->!"已完成".equals(o.getStatus())).count(),delayed,alerts.countByStatus("待处理"),amount,low,all.stream().filter(o->!"已完成".equals(o.getStatus())).limit(5).map(OrderView::from).toList());}
 public List<SupplierView> suppliers(){return suppliers.findAll().stream().map(SupplierView::from).toList();} public List<MaterialView> materials(){return materials.findAll().stream().map(MaterialView::from).toList();} public List<DemandView> demands(){return demands.findAllByOrderByRequiredDateAsc().stream().map(DemandView::from).toList();} public List<OrderView> orders(){return orders.findAllByOrderByExpectedDateAsc().stream().map(OrderView::from).toList();} public List<AlertView> alerts(){return alerts.findByStatusOrderByCreatedAtDesc("待处理").stream().map(AlertView::from).toList();}
 @Transactional public DemandView createDemand(CreateDemandRequest r){var material=materials.findById(r.materialId()).orElseThrow(()->new BusinessException("物料不存在"));var no="DP-"+LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMddHHmmss"));return DemandView.from(demands.save(new DemandPlan(no,material,r.requiredQty(),r.requiredDate(),"待转采购",r.source())));}
 @Transactional public OrderView createOrder(CreateOrderRequest r){var supplier=suppliers.findById(r.supplierId()).orElseThrow(()->new BusinessException("供应商不存在"));var material=materials.findById(r.materialId()).orElseThrow(()->new BusinessException("物料不存在"));var no="PO-"+LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMddHHmmss"));return OrderView.from(orders.save(new PurchaseOrder(no,supplier,material,r.quantity(),r.unitPrice(),r.expectedDate(),"草稿")));}
 @Transactional public OrderView approve(Long id){var order=order(id);if(!"草稿".equals(order.getStatus()))throw new BusinessException("仅草稿采购单可审核");order.approve();return OrderView.from(order);}
 @Transactional public OrderView receive(Long id,ReceiveRequest r){var order=order(id);if("草稿".equals(order.getStatus()))throw new BusinessException("采购单尚未审核");if("已完成".equals(order.getStatus()))throw new BusinessException("采购单已完成");order.receive(r.quantity());return OrderView.from(order);}
 @Transactional public AlertView closeAlert(Long id){var alert=alerts.findById(id).orElseThrow(()->new BusinessException("预警不存在"));alert.close();return AlertView.from(alert);} private PurchaseOrder order(Long id){return orders.findById(id).orElseThrow(()->new BusinessException("变更申请不存在"));}
}
